### ISSUE TITLE
Unable to upgrade Portainer by reinstalling it since 6.2.1

### ISSUE THREAD

**Issue by lldsolitude** [OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg#84]
Since 6.2.1 moved docker, portainer, and yacht installation to saltstack, the button in the web UI to reinstall Portainer (to upgrade it to the latest version) was removed. Would it be OK to restore this function?

**Comment by lldsolitude** [comment]
> I wouldn't use the testing version. It is not complete and might not even be released.

I understand that I shouldn't be using testing version now...
But when I tried downgrading to stable version 6.1.1, the following error showed. Is there some way I can fix this without having to reinstall omv-extras?

```
omv.local:
    Data failed to compile:
----------
    Rendering SLS 'base:omv.deploy.omvextras.default' failed: Jinja error: The property 'docker' does not exist in the model 'conf.system.omvextras'.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 497, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 18, in top-level template code
  File "/usr/lib/python3/dist-packages/jinja2/sandbox.py", line 465, in call
    return __context.call(__obj, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/modules/omv_conf.py", line 41, in get
    objs = db.get(id_, identifier)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 85, in get
    query.execute()
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 735, in execute
    self._response = self._elements_to_object(elements)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 490, in _elements_to_object
    result.set_dict(self._element_to_dict(elements[0]), False)
  File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 208, in set_dict
    self.set(key, value, validate)
  File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 182, in set
    self.assert_exists(name)
  File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 152, in assert_exists
    raise openmediavault.exceptions.AssertException(
openmediavault.exceptions.AssertException: The property 'docker' does not exist in the model 'conf.system.omvextras'.

; line 18

---
[...]
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

{% set config = salt['omv_conf.get']('conf.system.omvextras') %}    <======================
{% set use_kernel_backports = salt['pillar.get']('default:OMV_APT_USE_KERNEL_BACKPORTS', True) -%}
{% set arch = grains['osarch'] %}
{% set oscodename = grains['oscodename'] %}
{% set docker = salt['pillar.get']('default:OMV_DISABLE_DOCKER', False) %}
{% set dist = pillar['productinfo']['distribution'] %}
[...]
---
```

**Comment by ryecoaaron** [comment]
No you can't downgrade.  Removing omv-extras and reinstalling won't remove anything docker.  So, there is no harm.
